
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
  
public void setVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
 
/**
 *
 * @author Iviwe Cabangana
 */
  public class Developers extends javax.swing.JFrame {

    private String[] developers = {"Mike Smith", "Edward Harrison", "Samantha Paulson", "Glenda Oberholzer"};
    private String[] taskNames = {"Create Login", "Create Add Features", "Create Reports", "Add Arrays"};
    private int[] taskDurations = {5, 8, 2, 11};
    private String[] taskStatuses = {"To Do", "Doing", "Done", "To Do"};    
        private Object tblModel;

    
/**
     * Creates new form DEVELOPERS
     */
    public Developers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        ShowReport = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        TaskName = new javax.swing.JTextField();
        TaskNumber = new javax.swing.JTextField();
        TaskDescription = new javax.swing.JTextField();
        DeveloperDetails = new javax.swing.JTextField();
        TaskDuration = new javax.swing.JTextField();
        TaskID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        TaskStatus = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DEVELOPERS");

        jLabel3.setText("TASK NUMBER:");

        jLabel4.setText("TASK DESCRIPTION:");

        jLabel5.setText("DEVELOPER DETAILS:");

        jLabel6.setText("TASK DURATION:");

        jLabel7.setText("TASK ID:");

        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        ShowReport.setText("SHOW REPORT");
        ShowReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowReportActionPerformed(evt);
            }
        });

        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        TaskName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskNameActionPerformed(evt);
            }
        });

        TaskNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskNumberActionPerformed(evt);
            }
        });

        TaskDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDescriptionActionPerformed(evt);
            }
        });

        TaskDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDurationActionPerformed(evt);
            }
        });

        jLabel8.setText("TASK NAME:");

        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TASK NAME:", "TASK NUMBER", "TASK DESCRIPTION", "DEVELOPER DETAILS", "TASK DURATION", "TASK ID", "TASK STATUS"
            }
        ));
        jScrollPane1.setViewportView(TABLE);

        jLabel9.setText("TASK STATUS:");

        TaskStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskStatusActionPerformed(evt);
            }
        });

        Search.setText("SEARCH");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Add)
                .addGap(88, 88, 88)
                .addComponent(ShowReport)
                .addGap(92, 92, 92)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete)
                .addGap(75, 75, 75)
                .addComponent(Exit)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TaskDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TaskNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TaskDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TaskStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeveloperDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TaskID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TaskNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TaskDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DeveloperDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaskDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaskID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TaskStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowReport)
                    .addComponent(Exit)
                    .addComponent(Add)
                    .addComponent(Search)
                    .addComponent(Delete))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) TABLE.getModel();
model.addRow(new Object[]{
    TaskName.getText(),
    TaskNumber.getText(),
    TaskDescription.getText(),
    DeveloperDetails.getText(),
    TaskDuration.getText(),
    TaskID.getText(),
    TaskStatus.getText(),
});
    
 
    
    
    }//GEN-LAST:event_AddActionPerformed

    private void TaskNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskNameActionPerformed

    private void TaskDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskDescriptionActionPerformed

    private void TaskNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskNumberActionPerformed

    private void TaskDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskDurationActionPerformed

    private void TaskStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskStatusActionPerformed

    private void ShowReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowReportActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Coming Soon!");
        
    }//GEN-LAST:event_ShowReportActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Have a great day!");
                new WELCOMEPAGE().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:

       {

int size = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter your task name:"));
        int i;
        for (i=0; i < size; i++) {
        
        String DeveloperDetails = JOptionPane.showInputDialog(null, "Enter Developer Details:");
        
        String search =  JOptionPane.showInputDialog(null, "Enter the task name of whic you are searching for:");

        for (int n = 0; n < size; n++) {
            if (DeveloperDetails.equalsIgnoreCase(search)) {
                JOptionPane.showMessageDialog(null, "Task found: " + TaskName + TaskNumber  + TaskDescription + DeveloperDetails + TaskID + TaskStatus);                return;
            }
}
        }
        JOptionPane.showMessageDialog(null, "Task not found");
    }

    
        String inputTask = JOptionPane.showInputDialog("Enter the task you want to search for:");
        if (inputTask != null && !inputTask.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid task name");
        }
    else JOptionPane.showInputDialog("Invalid Task name! Enter correct task name:");
    

 

    }//GEN-LAST:event_SearchActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:

      
    DefaultTableModel tblModel = (DefaultTableModel) TABLE.getModel();

    // delete row
    if (TABLE.getSelectedRowCount() == 1) {
        // if single row is selected then delete
        tblModel.removeRow(TABLE.getSelectedRow());
    } else {
        if (TABLE.getRowCount() == 0) {
            // if table is empty (no data) then display message
            JOptionPane.showMessageDialog(this, "Table is empty");
        } else {
            // if table is not empty but row is not selected or multiplied
            JOptionPane.showMessageDialog(this, "Please select a single row for delete");
        }
    }
}








    /*int size = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter what you would like to delete"));
        int i;
        for (int i = 0; i < size; i++) {
            if (DeveloperDetails[i].equals(DeveloperDetails)) {
JOptionPane.showMessageDialog(null, "Task is deleted!");*/
// Shift elements to the left to "delete" the task


/* for (int j = i; j < DeveloperDetails.length - 1; j++) {
DeveloperDetails[j] = DeveloperDetails[j + 1];
TaskName[j] = TaskName[j + 1];
TaskDuration[j] = TaskDuration[j + 1];
TaskStatus[j] = TaskStatus[j + 1];

// Nullify the last elements
DeveloperDetails[DeveloperDetails.length - 1] = null;
TaskName[TaskName.length - 1] = null;
TaskDuration[TaskDuration.length - 1] = 0;
TaskStatus[TaskStatus - 1] = null;*/
/*JOptionPane.showMessageDialog(null, "Task has been deleted");*/
/*} else {
}*/
    }
            /*else JOptionPane.showMessageDialog(null, "Task has not been deleted. Try again!");
                }
} 

    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

 /*DeveloperDetails developerDetails = new DeveloperDetails();
    developerDetails.deleteTask();
}
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEVELOPERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEVELOPERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEVELOPERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEVELOPERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                //new DEVELOPERS().setVisible(true);
                this.setVisible(true);
               }
            public void setVisible(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField DeveloperDetails;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Search;
    private javax.swing.JButton ShowReport;
    private javax.swing.JTable TABLE;
    private javax.swing.JTextField TaskDescription;
    private javax.swing.JTextField TaskDuration;
    private javax.swing.JTextField TaskID;
    private javax.swing.JTextField TaskName;
    private javax.swing.JTextField TaskNumber;
    private javax.swing.JTextField TaskStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables



